### ISSUE TITLE
Alerts container and alerts_plugins container reboot loops

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#1060]
Hey all,

So in working with my MozDef docker containers I ran a `make stop; make run` the other day and have been getting reboot loops on both the alerts and alerts_plugins containers. Both have been complaining about importing configlib with logs like
```
Traceback (most recent call last):
  File "alert_worker.py", line 14, in <module>
    from configlib import getConfig, OptionParser
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/configlib/__init__.py", line 1, in <module>
    from configlib import getConfig
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/configlib/configlib.py", line 6, in <module>
    from everett.manager import ConfigIniEnv
ImportError: cannot import name ConfigIniEnv
```
My alerts container is stable after commenting out all alerts in config.py and when trying to install configlib manually I get the following error
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 326, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 834, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1037, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/six.pyc'
```
Running a pip install of the requirements file gives similar issues for other packages as well.

I'm bringing up a new instance now to see if the issue comes in with a fresh build or not.

**Comment by pwnbus** [comment]
This issue has been recently fixed (https://github.com/mozilla/MozDef/pull/1032), and was due to a dependency of ours not version locking a dependency.

**Comment by darakian** [comment]
Ah, my bad. Should have searched first. Do I need to rebuild the containers to fix it?

**Comment by pwnbus** [comment]
Yeah, you'll need to `git pull` and then rebuild the containers unfortunately.

**Comment by darakian** [comment]
Cool thanks.
