### ISSUE TITLE
Celery Jobs Failing in Cloud After Password Randomization

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#1241]
```
[2019-05-01 21:11:16,582: DEBUG/MainProcess] removing tasks from inqueue until task handler finished

 -------------- celery@aefce3697811 v4.1.0 (latentcall)
---- **** -----
--- * ***  * -- Linux-4.14.109-99.92.amzn2.x86_64-x86_64-with-centos-7.6.1810-Core 2019-05-01 21:11:15
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         alerts:0x7effaf428650
- ** ---------- .> transport:   amqp://mozdef:**@rabbitmq:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery-default   exchange=celery-default(direct) key=celery-default


[tasks]
  . bruteforce_ssh.AlertBruteforceSsh
  . cloudtrail_deadman.AlertCloudtrailDeadman
  . cloudtrail_logging_disabled.AlertCloudtrailLoggingDisabled
  . guard_duty_probe.AlertGuardDutyProbe
  . unauth_ssh.AlertUnauthSSH

DEBUG starting AlertCloudtrailLoggingDisabled
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'REDACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
DEBUG ES configured
DEBUG starting AlertCloudtrailDeadman
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'REDACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
DEBUG ES configured
DEBUG starting AlertUnauthSSH
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'REDACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
DEBUG ES configured
DEBUG starting AlertGuardDutyProbe
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'REDACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
DEBUG ES configured
DEBUG starting AlertBruteforceSsh
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'REDACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
DEBUG ES configured
[2019-05-01 21:14:38,709: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2019-05-01 21:14:38,709: DEBUG/MainProcess] | Worker: Building graph...
[2019-05-01 21:14:38,710: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, Beat, StateDB, Consumer}
[2019-05-01 21:14:38,715: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2019-05-01 21:14:38,715: DEBUG/MainProcess] | Consumer: Building graph...
[2019-05-01 21:14:38,719: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Tasks, Control, Gossip, Agent, event loop}
[2019-05-01 21:14:38,721: DEBUG/MainProcess] | Worker: Starting Hub
[2019-05-01 21:14:38,721: DEBUG/MainProcess] ^-- substep ok
[2019-05-01 21:14:38,721: DEBUG/MainProcess] | Worker: Starting Pool
[2019-05-01 21:14:38,735: DEBUG/MainProcess] ^-- substep ok
[2019-05-01 21:14:38,736: DEBUG/MainProcess] | Worker: Starting Beat
[2019-05-01 21:14:38,738: DEBUG/MainProcess] ^-- substep ok
[2019-05-01 21:14:38,738: DEBUG/MainProcess] | Worker: Starting Consumer
[2019-05-01 21:14:38,738: DEBUG/MainProcess] | Consumer: Starting Connection
[2019-05-01 21:14:38,744: INFO/Beat] beat: Starting...
[2019-05-01 21:14:38,753: CRITICAL/MainProcess] Unrecoverable error: AccessRefused(403, u'ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.', (0, 0), u'')
Traceback (most recent call last):
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 407, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 414, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 438, in ensure_connected
    callback=maybe_shutdown,
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/connection.py", line 288, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/connection.py", line 481, in on_inbound_method
    method_sig, payload, content,
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/amqp/connection.py", line 603, in _on_close
    (class_id, method_id), ConnectionError)
AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
[2019-05-01 21:14:38,755: DEBUG/MainProcess] | Worker: Closing Hub...
[2019-05-01 21:14:38,756: DEBUG/MainProcess] | Worker: Closing Pool...
[2019-05-01 21:14:38,756: DEBUG/MainProcess] | Worker: Closing Beat...
[2019-05-01 21:14:38,756: DEBUG/MainProcess] | Worker: Closing Consumer...
[2019-05-01 21:14:38,756: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2019-05-01 21:14:38,757: DEBUG/MainProcess] | Worker: Stopping Beat...
[2019-05-01 21:14:38,757: INFO/MainProcess] beat: Shutting down...
[2019-05-01 21:14:38,757: DEBUG/MainProcess] | Worker: Stopping Pool...
[2019-05-01 21:14:39,760: DEBUG/MainProcess] | Worker: Stopping Hub...
[2019-05-01 21:14:39,760: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2019-05-01 21:14:39,760: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2019-05-01 21:14:39,760: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2019-05-01 21:14:39,761: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2019-05-01 21:14:39,761: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2019-05-01 21:14:39,761: DEBUG/MainProcess] | Consumer: Shutdown Connection...

 -------------- celery@aefce3697811 v4.1.0 (latentcall)
---- **** -----
--- * ***  * -- Linux-4.14.109-99.92.amzn2.x86_64-x86_64-with-centos-7.6.1810-Core 2019-05-01 21:14:38
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         alerts:0x7effcfc01650
- ** ---------- .> transport:   amqp://mozdef:**@rabbitmq:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery-default   exchange=celery-default(direct) key=celery-default


[tasks]
  . bruteforce_ssh.AlertBruteforceSsh
  . cloudtrail_deadman.AlertCloudtrailDeadman
  . cloudtrail_logging_disabled.AlertCloudtrailLoggingDisabled
  . guard_duty_probe.AlertGuardDutyProbe
  . unauth_ssh.AlertUnauthSSH

[2019-05-01 21:14:39,761: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
DEBUG starting AlertCloudtrailLoggingDisabled
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'READACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
DEBUG ES configured
DEBUG starting AlertCloudtrailDeadman
DEBUG {'mquser': 'mozdef', 'alertexchange': 'alerts', 'alertqueue': 'mozdef.alert', 'mqport': 5672, 'mqserver': 'rabbitmq', 'mqpassword': 'READACTED_BY_ANDREW'}
DEBUG {'servers': ['http://vpc-mozdef-mozdef-yemjpbnpw8xb-fefaxizb4buw567budiqgkbmki.us-west-2.es.amazonaws.com:80']}
ERROR Exception while configuring kombu for alerts: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
```

**Comment by andrewkrug** [comment]
This was taken care of by simply taking env var interpolation out of the one liner that created the MozDef user in rabbit and granted access to the vhost.
