### ISSUE TITLE
Unable to install pip requirements on Mac OS X

### ISSUE THREAD

**Issue by pwnbus** [mozilla/MozDef#1300]
Due to this change https://github.com/mozilla/MozDef/commit/6d05bc6650abed99afe57ea3a334d83f26e0d484#diff-b4ef698db8ca845e5845c4618278f29aR44  when I run `pip install -r requirements.txt` on a Mac, it now fails:
```
Collecting pycurl==7.43.0.2 (from -r requirements.txt (line 44))
  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Using curl-config (libcurl 7.54.0)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-UIRZdq/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-UIRZdq/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-UIRZdq/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-UIRZdq/pycurl/setup.py", line 316, in configure_unix
        specify the SSL backend manually.''')
    __main__.ConfigurationError: Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-UIRZdq/pycurl/
```

**Comment by pwnbus** [comment]
I believe the work around is to do `PYCURL_SSL_LIBRARY=openssl pip install -r requirements.txt`, however, it breaks as well:
```
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py) ... error
  ERROR: Complete output from command /Users/bmyers/src/mozdef-env/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-IsLiTh/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-wheel-c6SJYc --python-tag cp27:
  ERROR: Using curl-config (libcurl 7.54.0)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-2.7
  creating build/lib.macosx-10.11-x86_64-2.7/curl
  copying python/curl/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/curl
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building 'pycurl' extension
  creating build/temp.macosx-10.11-x86_64-2.7
  creating build/temp.macosx-10.11-x86_64-2.7/src
  clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPYCURL_VERSION="7.43.0.2" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/docstrings.c -o build/temp.macosx-10.11-x86_64-2.7/src/docstrings.o
  In file included from src/docstrings.c:4:
  src/pycurl.h:164:13: fatal error: 'openssl/ssl.h' file not found
  #   include <openssl/ssl.h>
              ^~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycurl
  Running setup.py clean for pycurl
Failed to build pycurl
Installing collected packages: pycurl
  Running setup.py install for pycurl ... error
    ERROR: Complete output from command /Users/bmyers/src/mozdef-env/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-IsLiTh/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-record-WOn5IV/install-record.txt --single-version-externally-managed --compile --install-headers /Users/bmyers/src/mozdef-env/bin/../include/site/python2.7/pycurl:
    ERROR: Using curl-config (libcurl 7.54.0)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    creating build/lib.macosx-10.11-x86_64-2.7/curl
    copying python/curl/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/curl
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'pycurl' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/src
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPYCURL_VERSION="7.43.0.2" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/docstrings.c -o build/temp.macosx-10.11-x86_64-2.7/src/docstrings.o
    In file included from src/docstrings.c:4:
    src/pycurl.h:164:13: fatal error: 'openssl/ssl.h' file not found
    #   include <openssl/ssl.h>
                ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/bmyers/src/mozdef-env/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-IsLiTh/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-record-WOn5IV/install-record.txt --single-version-externally-managed --compile --install-headers /Users/bmyers/src/mozdef-env/bin/../include/site/python2.7/pycurl" failed with error code 1 in /private/var/folders/bw/10mkyfzx5kvbhhtm33prh58h0000gn/T/pip-install-IsLiTh/pycurl/
```

**Comment by pwnbus** [comment]
In the meantime, I just simply comment out https://github.com/mozilla/MozDef/blob/master/requirements.txt#L44 since I'm not using sqs as a replacement of rabbitmq and everything works fine.
