### ISSUE TITLE
Python3 with proxy now causes errors in boto core library

### ISSUE THREAD

**Issue by pwnbus** [mozilla/MozDef#1349]
When behind a proxy, and using python3, we're now getting a stack trace from within the boto library:
```
Traceback (most recent call last):
 File "/opt/mozdef/envs/mozdef/cron/sqs_queue_status.py", line 141, in <module>
 main()
 File "/opt/mozdef/envs/mozdef/cron/sqs_queue_status.py", line 117, in main
 getQueueSizes()
 File "/opt/mozdef/envs/mozdef/cron/sqs_queue_status.py", line 54, in getQueueSizes
 eventTaskQueue = mqConn.get_queue(exchange)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/sqs/connection.py", line 521, in get_queue
 return self.get_object('GetQueueUrl', params, Queue)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/connection.py", line 1192, in get_object
 response = self.make_request(action, params, path, verb)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/connection.py", line 1116, in make_request
 return self._mexe(http_request)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/connection.py", line 913, in _mexe
 self.is_secure)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/connection.py", line 705, in get_http_connection
 return self.new_http_connection(host, port, is_secure)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/connection.py", line 747, in new_http_connection
 connection = self.proxy_ssl(host, is_secure and 443 or 80)
 File "/opt/mozdef/envs/python/lib/python3.6/site-packages/boto/connection.py", line 796, in proxy_ssl
 sock.sendall("CONNECT %s HTTP/1.0\r\n" % host)
TypeError: a bytes-like object is required, not 'str'
```

I found https://github.com/boto/boto/pull/3699 but this never got merged, and after talking to Gene, I think we'll want to switch over to using boto3.

**Comment by pwnbus** [comment]
This also appears to be erroring out on https://github.com/mozilla/MozDef/blob/master/cron/sqs_queue_status.py , https://github.com/mozilla/MozDef/blob/master/cron/update_ip_list.py and https://github.com/mozilla/MozDef/blob/master/cron/createIPBlockList.py
