### ISSUE TITLE
Move to ES6 causes invalid_type_name_exception for existing index

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1386]
In updating the AWS stack today to the current code, it looks like the update causes problems in the current index which is on ES 5.6 in AWS.

```
POST http://vpc-mozdef-mozdef-2f5iwtlytavk-pntm24lz2fdsrod3j4k4d7couy.us-west-2.es.amazonaws.com:80/events/_doc [status:400 request:0.006s]
2019-07-19T19:20:24.063964+00:00 - esworker_cloudtrail.py - ERROR - RequestError(400, 'invalid_type_name_exception', "Document mapping type name can't start with '_', found: [_doc]")
Traceback (most recent call last):
  File "esworker_cloudtrail.py", line 347, in on_message
    bulk=bulk
  File "/opt/mozdef/envs/mozdef/mozdef_util/mozdef_util/elasticsearch_client.py", line 168, in save_event
    return self.__save_document(index=index, body=event, doc_id=doc_id, bulk=bulk)
  File "/opt/mozdef/envs/mozdef/mozdef_util/mozdef_util/elasticsearch_client.py", line 145, in __save_document
    return self.es_connection.index(index=index, doc_type=DOCUMENT_TYPE, id=doc_id, body=body)
  File "/opt/mozdef/envs/python/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/mozdef/envs/python/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 319, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/opt/mozdef/envs/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/opt/mozdef/envs/python/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/mozdef/envs/python/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'invalid_type_name_exception', "Document mapping type name can't start with '_', found: [_doc]")
```

**Comment by pwnbus** [comment]
This is currently due to the fact that cloudy mozdef uses Elasticsearch 5. Once we update that to use Elasticsearch 6, this error will go away (this is due to ES moving towards using _doc as the _type for here on forward)

**Comment by pwnbus** [comment]
Implemented in https://github.com/mozilla/MozDef/pull/1387
