### ISSUE TITLE
Change python virtualenv to /opt/mozdef/envs/python

### ISSUE THREAD

**Issue by pwnbus** [mozilla/MozDef#421]
This means we need to modify each cron/*.sh file to point to the new python binary.

**Comment by scriptonist** [comment]
Hey can I take this up ?.

**Comment by pwnbus** [comment]
Yeah of course! I'll unassign myself. In order to assign you to this item, we'll need to add you as a contributor.

**Comment by scriptonist** [comment]
@pwnbus Thank for assigning me this issue. I'm a beginner and i'm very new to open source contributions. I will try my best to resolve this issue. I will  keep you updated with my progress.Please help me out if get stuck.

**Comment by pwnbus** [comment]
Not a problem! Any contribution is a good contribution :)     If you run into any problems, feel free to let me know and we can work through them!

**Comment by scriptonist** [comment]
@pwnbus I'm not able to build the image. when Irun `cd docker && sudo make build ` I'm getting following error
`make: *** No rule to make target `build'.  Stop.`

**Comment by pwnbus** [comment]
@scriptonist Run the make command from the project root, so don't 'cd docker'

**Comment by scriptonist** [comment]
@pwnbus same error when running from project root

**Comment by pwnbus** [comment]
@scriptonist The makefile is located here https://github.com/mozilla/MozDef/blob/master/Makefile  Have you updated your local copy of mozdef recently? "git pull origin master"? Do you see other files that are in the project root as well (requirements.txt, README.md etc?)

**Comment by pwnbus** [comment]
Ohh, I'm sorry, it's not make build, you need to run "make single-build" and "make single-run".

**Comment by pwnbus** [comment]
Once you run make single-run once, you can do "make single-rebuild" which runs a build, stops the current container, and reruns the updated container. This is helpful for debugging/developing.

**Comment by pwnbus** [comment]
It appears as though the docs are outdated, so I apologize for that. I'll create an issue to update those, all of this docker stuff is fairly recent, so we'll work through on ironing out any issues :)

**Comment by scriptonist** [comment]
@pwnbus I'm getting some npm errors when running the build
```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@4.7.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory `/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory `/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-92-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /node_modules/bcrypt
gyp ERR! node -v v4.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:854:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
node-pre-gyp ERR! System Linux 4.4.0-92-generic
node-pre-gyp ERR! command "/usr/bin/node" "/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_modules/bcrypt
node-pre-gyp ERR! node -v v4.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/node_modules/bcrypt/lib/binding' (1)
npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "source-map-support@0.4.2" "semver@5.3.0" "fibers@1.0.13" "amdefine@1.0.0" "underscore@1.8.3" "bcrypt"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

```

**Comment by jeffbryner** [comment]
You are getting the same thing I got: "make: g++: Command not found"

The docker container is missing a dependency to build bcrypt. You can find the fix in this pull request: https://github.com/mozilla/MozDef/pull/454

**Comment by pwnbus** [comment]
@scriptonist Since we haven't heard anything from ya for a month, we're gonna close this PR. 

Feel free to address the comments and commit the fixes, and we can either reopen this PR, or create a new one :)

**Comment by scriptonist** [comment]
@pwnbus Sorry! I totally forgot about this. I believe now all looks good and submitted a PR.Please review and suggest fixes if any.
