### ISSUE TITLE
fix loginput index.py: Attribute Error None Type object has no attribute channel on mq timeout

### ISSUE THREAD

**Issue by netantho** [mozilla/MozDef#61]
On rabbitmq timeout, kombu/pyamqp goes crazy:

```
    Traceback (most recent call last):
    File "/home/mozdef/envs/mozdef/lib/python2.7/site-packages/bottle.py", line 764, in _handle
    return route.call(**args)
    File "/home/mozdef/envs/mozdef/lib/python2.7/site-packages/bottle.py", line 1575, in wrapper
    rv = callback(*a, **ka)
    File "/home/mozdef/envs/mozdef/loginput/index.py", line 94, in cefindex
    ensurePublish(cefDict,exchange=eventTaskExchange,routing_key=options.taskexchange)
    File "/home/mozdef/envs/mozdef/lib/python2.7/site-packages/kombu/connection.py", line 462, in _ensured
    new_channel = self.channel()
    File "/home/mozdef/envs/mozdef/lib/python2.7/site-packages/kombu/connection.py", line 246, in channel
    chan = self.transport.create_channel(self.connection)
    File "/home/mozdef/envs/mozdef/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 87, in create_channel
    return connection.channel()
    AttributeError: 'NoneType' object has no attribute 'channel'
```

Some people had similar issues with celery:
- https://bugzilla.mozilla.org/show_bug.cgi?id=663555
- https://bugzilla.mozilla.org/show_bug.cgi?id=648126

**Comment by jeffbryner** [comment]
I think this is long been fixed.
